import { type RouteConfig, route } from "@react-router/dev/routes";

export default [
  route("/", "./pages/Home.jsx"),
  route("/academic", "./pages/Education.jsx"),
  route("/professional", "./pages/Work.jsx"),
  route("/projects", "./pages/Projects.jsx"),
  route("/projects/digraph-explorer", "./pages/projects/DigraphExplorer.jsx"),
  route("/projects/prettymath", "./pages/projects/EducationalGames.jsx"),
  route("/projects/wine-exports-viz", "./pages/projects/Comtrade.jsx"),
  route("/projects/mastermind", "./pages/projects/MastermindGame.jsx"),
  route("/projects/fraud-detection", "./pages/projects/FraudDetection.jsx"),
  route("/projects/jobmaster", "./pages/projects/JobMaster.jsx"),
  route("/projects/macaroni", "./pages/projects/Macaroni.jsx"),
  route("/projects/early-warning-signals", "./pages/projects/EarlyWarningSignals.jsx"),
  route("/projects/ps-indicator", "./pages/projects/PSIndicator.jsx"),
  route("/projects/multidim-ews", "./pages/projects/MultidimEWS.jsx"),
  route("/projects/ps-robustness", "./pages/projects/PSRobustness.jsx"),
  route("/projects/adaptive-mesh", "./pages/projects/AdaptiveMesh.jsx"),
  route("/projects/jobsearch-agent", "./pages/projects/JobSearchAgent.jsx"),
  route("/projects/steam-market-gap", "./pages/projects/SteamMarketGap.jsx"),
  route("/projects/private-label", "./pages/projects/PrivateLabel.jsx"),
  route("/projects/pl-dashboard", "./pages/redirects/PLDashboardRedirect.jsx"),
  route("/blog", "./pages/Blog.jsx"),
  route("/blog/:id", "./pages/BlogPost.jsx"),
  route("/blog/tag/:tag", "./pages/Blog.jsx", { id: "blog-by-tag" }),
  route("/travels", "./pages/Travels.jsx"),
  route("/travel/vanlife", "./pages/travel/Vanlife.jsx"),
  route("/cv", "./pages/redirects/CVRedirect.jsx"),
  route("/tutor", "./pages/Tutor.jsx"),
  route("/freelance", "./pages/Freelance.jsx"),
  route("*?", "./pages/NotFound.jsx"),
] satisfies RouteConfig;
